apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-coldstart-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-coldstart-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
