apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30090  # Você pode definir um NodePort específico ou deixar Kubernetes escolher um
  selector:
    app: prometheus
