datadog:
  apiKey: "1e413dd2173bc9db14528cba649893c5b643643b"
  site: "datadoghq.com"
  tags:
    - env:local
  kubeStateMetricsEnabled: true
  clusterName: "local-cluster"
  collectEvents: true
  leaderElection: true
  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
  logs:
    enabled: true
  containers:
    logs:
      enabled: true
   hostname: "custom-hostname"