apiVersion: apps/v1
kind: Deployment
metadata:
  name: iobound-deployment
  labels:
    app: iobound
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iobound
  template:
    metadata:
      labels:
        app: iobound
    spec:
      containers:
        - name: iobound-container
          image: soaresmaric/tcc-iobound:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
