apiVersion: v1
kind: Service
metadata:
  name: iobound-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: iobound
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
