global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  - job_name: 'iobound'
    static_configs:
      - targets: ['10.98.221.146:8080']
        labels:
          instance: 'iobound-instance'
