apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000
  selector:
    app: registry
  type: NodePort
