apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iobound-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: iobound
  endpoints:
    - port: http
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - default
